import { StyleSheet } from "react-native";
import { AppTheme } from "../../theme/light";

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: theme.colors.bg },
    container: { flex: 1 },
    scroll: { flex: 1 },
    scrollContent: { paddingBottom: 8 },

    profileSection: {
      alignItems: "center",
      paddingHorizontal: 20,
      paddingBottom: 16,
    },
    avatarWrapper: {
      width: 120,
      height: 120,
      borderRadius: 60,
      borderWidth: 4,
      borderColor: theme.colors.surface,
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 6,
      marginBottom: 12,
    },
    avatar: { width: "100%", height: "100%" },
    profileName: {
      fontWeight: "700",
      fontSize: 20,
      color: theme.colors.textDark,
      marginBottom: 4,
    },
    profileHandle: {
      fontSize: 14,
      color: theme.colors.textMid,
      marginBottom: 16,
    },
    bioCard: {
      flexDirection: "row",
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 16,
      padding: 16,
      gap: 12,
      elevation: 2,
    },
    bioIconBg: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.colors.greenLight,
      alignItems: "center",
      justifyContent: "center",
    },
    bioText: {
      flex: 1,
      fontSize: 14,
      color: theme.colors.textDark,
      lineHeight: 22,
    },

    infoRow: {
      flexDirection: "row",
      alignItems: "center",
      marginHorizontal: 20,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 10,
      marginBottom: 16,
    },
    infoLabel: {
      flex: 1,
      fontSize: 14,
      color: theme.colors.textMid,
      marginLeft: 8,
    },
    infoValue: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.colors.textDark,
    },

    statsRow: {
      flexDirection: "row",
      marginHorizontal: 20,
      gap: 10,
      marginBottom: 4,
    },

    favPlantCard: {
      flexDirection: "row",
      marginHorizontal: 20,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 16,
      padding: 16,
      alignItems: "center",
      gap: 12,
      overflow: "hidden",
      elevation: 2,
    },
    favPlantImg: { width: 80, height: 80, borderRadius: 20 },
    favPlantInfo: { flex: 1 },
    favPlantLabel: {
      fontSize: 11,
      fontWeight: "600",
      color: theme.colors.green,
      letterSpacing: 0.6,
      marginBottom: 4,
    },
    favPlantName: {
      fontSize: 18,
      fontWeight: "700",
      color: theme.colors.textDark,
      marginBottom: 2,
    },
    favPlantFamily: {
      fontSize: 14,
      color: theme.colors.textMid,
      marginBottom: 2,
    },
    favPlantSince: { fontSize: 12, color: theme.colors.textMid, opacity: 0.7 },

    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 20,
      marginBottom: 10,
    },
    sectionTitle: {
      fontSize: 13,
      fontWeight: "600",
      color: theme.colors.textMid,
      letterSpacing: 0.7,
    },
    categoriesScroll: { marginBottom: 4 },
    categoriesContent: { paddingHorizontal: 20, gap: 10 },

    badgesRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      paddingHorizontal: 20,
      gap: 8,
      marginBottom: 6,
    },

    completionCard: {
      marginHorizontal: 20,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 16,
      padding: 16,
      marginBottom: 12,
    },
    completionTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 10,
    },
    completionTitleRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    completionTitle: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.colors.textDark,
    },
    completionPct: {
      fontSize: 14,
      fontWeight: "700",
      color: theme.colors.green,
    },
    progressBg: {
      height: 8,
      backgroundColor: theme.colors.greenPale,
      borderRadius: 999,
      overflow: "hidden",
      marginBottom: 8,
    },
    progressFill: {
      height: "100%",
      backgroundColor: theme.colors.green,
      borderRadius: 999,
    },
    completionHint: { fontSize: 12, color: theme.colors.textMid },

    potdCard: {
      marginHorizontal: 20,
      backgroundColor: theme.colors.greenLight,
      borderWidth: 1,
      borderColor: "rgba(57,121,73,0.2)",
      borderRadius: 16,
      padding: 16,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    potdIconBg: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: "rgba(57,121,73,0.15)",
      alignItems: "center",
      justifyContent: "center",
    },
    potdInfo: { flex: 1 },
    potdLabel: {
      fontSize: 11,
      fontWeight: "600",
      color: theme.colors.green,
      letterSpacing: 0.6,
      marginBottom: 2,
    },
    potdName: {
      fontSize: 14,
      fontWeight: "700",
      color: theme.colors.textDark,
      marginBottom: 2,
    },
    potdDesc: { fontSize: 12, color: theme.colors.textMid },
  });
